### ISSUE TITLE
make_predict_data.exe 制作predict.db时出现Error: invalid digit found in string

### ISSUE THREAD

**Issue by han-fan** [rime/librime-predict#21]
![image](https://github.com/rime/librime-predict/assets/67369963/c9925d52-2c6c-4507-90dc-efb3f7bc28c2)
你好，我用在这里下的main.rs编译器出来的make_predict_data.exe 去制作perdict.db时，出现了Error: invalid digit found in string。修改perdict.txt,无效。

想问下有什么解决方法么？

谢谢！

**Comment by lotem** [comment]
不需要用 `make_predict_data` 处理。直接喂给 [build_predict](https://github.com/rime/librime-predict/blob/master/tools/build_predict.cc)

**Comment by han-fan** [comment]
> 不需要用 `make_predict_data` 处理。直接喂给 [build_predict![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAATr4AAE6+AGeOBvEAAAA3klEQVQ4y83SPUpDURAF4M8YooUiIi7BQBaQ2lqirZjnVrIFCwsLDbbZgLoAO8FC7EJcgNgZUpvYTOByee/513hguDB3zpm5cy5/xOovOI0qgUZJ5FjDBbbxnF5s4hHjLPYz8jVmOFwmm0n3PdzhJXIreM06H6OP23y0LbyjVzJ2C8O8c51AGwOsB/kqyEd1m00FephiF5dfkZs1Vp0H8RQ3kS/iHJV6mmADJziLRe4kAkXlpwgsMI8Y4AEHP3nCPTohtMTbdwUKdCtq5+HQpEzgA09R0K5xa5p8tH+CT7aEK2vlnm2YAAAAAElFTkSuQmCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==)](https://github.com/rime/librime-predict/blob/master/tools/build_predict.cc)

`我没有C++的编程知识,我只会VB,编译build_predict.cc的时候各种找不到.h文件,
GOOGLE了好一长时间,也没有弄明白.
如果可以,能不能直接把制作perdict.db的程序发出来
或者说 共享下perdict.db文件 是怎么样构成的,我用别的语言写出相应的制作程序.

感谢!

**Comment by lotem** [comment]
這個插件要和 librime 一起編譯。

你要把什麼數據做成數據庫，做什麼用？
data/sample.txt 只是示例文件，說明數據的格式。

我沒法把程序發給你，因爲我跟你用的平臺二進制不兼容，你用不了。
對 librime 不熟悉的話，不建議自己研究如何製作數據庫文件～
